linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - elseif
  gofumpt:
    module-path: github.com/syndtr/goleveldb
    extra-rules: true

linters:
  enable:
    - megacheck
    - govet
    - gofumpt
    - gocritic
    - unconvert

  disable:
    - maligned
    - prealloc
  presets:
    - bugs
    - unused
  fast: false


run:
  concurrency: 5